### ISSUE TITLE
задача на первую неделю: подготовить данные и картинки

### ISSUE THREAD

**Issue by Amarchuk** [alekskryzh/X-galaxies#1]
- [x] скачать изображения с DESI Legacy, подобрав правильный размер. Тут нужно модифицировать мой код - сейчас скачивается из предыдущего релиза DR8, а самый последний DR9. Вероятно надо немного изменить ссылку на скачивание, поэкспериментируйте. По поводу размеров - или вручную, или попробуйте [photutils](https://photutils.readthedocs.io/en/stable/segmentation.html)
- [x] развернуть их горизонтально и обрезать, сохранить. Угол поворота тоже можно из photutils попытаться извлечь (можно использовать тот, что в колонке `pa` в `data/classifications.csv`)
- [x] нарисовать png картинки с изофотами и цветами *g-r*. Тут важно, чтоб изофоты очерчивали именно внутри структуру, и сама галактика была видна. Попробуйте подбирать изофоты автоматически (например с помощью `ZScaleInterval` из `astropy`).
- [x] посмотреть, для каких галактик есть данные Spitzer используя NED->Images->есть ли там 3.6 или 4.5 изображение (например у UGC10738 есть), оформить таблицей.

Хорошо, если все это будет оформлено в виде отдельных картинок и jupyter ноутбуков.

**Comment by Amarchuk** [comment]
Вот список галактик потестировать процесс на них (здесь полный путь до файла, надо только имя от него):

/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/966_80_1_line118.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1043_82_1_line19939.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1422_76_0_line2819__EON_39.676_6.909.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1466_34_0_line14620.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1589_24_0_line22427.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1594_63_0_line1297.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1674_60_0_line21679__EON_345.549_14.475.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1723_60_0_line12146__EON_190.304_18.604.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1850_50_0_line850.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1902_66_0_line15931__EON_236.371_26.603.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1910_23_1_line18487.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/1929_68_0_line22271.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/2015_16_1_line2021.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/2322_38_0_line12701.png
/mnt/sdb2/science/BPS_X_DESI/buckling/double_X/2488_52_1_line18561.png

**Comment by Amarchuk** [comment]
Будет несколько списков. Галактики с малыми барами из работы 2017го года:

1712_89_0_line7739__EON_140.351_19.567
1457_18_0_line11264__EON_180.421_4.770
1973_28_0_line12550__EON_194.556_28.948
1804_16_0_line10378__EON_170.647_20.704
1371_94_0_line12718__EON_196.196_3.905
1422_76_0_line2819__EON_39.676_6.909
2130_52_0_line15235__EON_226.162_38.011
2005_4_0_line21447__EON_342.032_28.295

**Comment by Amarchuk** [comment]
Подборка шестигранников (неполная, может быть мы уже по ним сможем понять):

1237_50_0_line1676__EON_21.856_-1.913
1973_28_0_line12550__EON_194.556_28.948
1401_46_0_line19910
EON_18.239_-0.345
EON_124.743_57.803
EON_137.160_32.593
EON_150.398_-2.994
EON_210.175_55.164
EON_206.090_55.856
EON_238.580_0.543
EON_245.501_58.527

**Comment by Amarchuk** [comment]
Основная выборка для оценки массы балджа (симметричные и яркие Х-структуры, желательно без пыли почти):

1237_70_0_line1682__EON_21.900_-1.105
1422_76_0_line2819__EON_39.676_6.909
1881_7_0_line7993__EON_143.943_24.379
1804_16_0_line10378__EON_170.647_20.704
1371_94_0_line12718__EON_196.196_3.905
1973_28_0_line12550__EON_194.556_28.948
1896_39_0_line13795__EON_208.851_25.292
2130_52_0_line15235__EON_226.162_38.011
1469_90_0_line15668__EON_232.554_7.767
1845_57_0_line21705__EON_345.959_22.314
1676_76_0_line22071__EON_351.297_15.200
803_97_0_line2129
1150_29_0_line1953
1937_45_0_line2281
804_63_1_line2514
724_45_0_line3075
1156_73_0_line3628
1248_24_0_line4035
1071_6_0_line4184
732_62_0_line4681
1707_6_0_line6339
1354_49_0_line6745
1181_30_0_line8916
1095_54_0_line9913
1975_51_0_line13632
1640_74_0_line13441
1043_82_1_line19939
2488_52_1_line18561
1315_49_0_line20646
1320_33_0_line22147
2007_19_0_line21884
EON_149.486_10.432
EON_183.977_6.401
EON_163.249_10.831
EON_247.192_39.463
EON_344.008_12.767

**Comment by Amarchuk** [comment]
Отлично! Вы хорошо справились. Единственное, что сейчас неудобно листать результаты - давайте еще сделаем сводные картинки. Для model и residual нам цвета не нужны, поэтому давайте оставим для каждой галактики 3х3: изофоты и цвета для исходной галактики и изофоты на вычете (и для трех полос). Лучше полосы по столбцам чтоб были, а сами файлы не в отдельных папках, а в одной (или по выборкам). Тогда просто будет понять, все ли в порядке, листая картинки. Сделайте (это просто), выложите и давайте созвонимся поговорить.

Про Spitzer странно, мне казалось что я проверил по ссылке. Ее и правда там нет, хотя данные для нее есть, например 
[в этой форме](https://sha.ipac.caltech.edu/applications/Spitzer/SHA/#id=SearchByPosition&RequestClass=ServerRequest&shortDesc=Position%20Search&isBookmarkAble=true&isDrillDownRoot=true). Можете используя этот сайт поискать еще раз (но пока это не так важно).

**Comment by alekskryzh** [comment]
Обновил ссылку на новый архив. Когда Вам было бы удобно созвониться? Завтра, послезавтра я могу в +- любое время.

**Comment by alekskryzh** [comment]
По Шпитцеру: искал по координатам, но нашёл данные только для шести галактик. Иногда ещё были какие-то записи о наблюдениях других объектов поблизости, но конкретно исследуемые галактики находились редко. 
Name, 3.6, 4.5
2005_4_0_line21447__EON_342.032_28.295   --  есть 3,6; нет 4,5
EON_183.977_6.401                                        --  есть 3,6; есть 4,5
EON_124.743_57.803                                      --  есть 3,6; есть 4,5
EON_210.175_55.164                                      --  есть 3,6; есть 4,5
EON_238.580_0.543                                        --  есть 3,6; есть 4,5
1793_23_1_line6652                                       --  есть 3,6; есть 4,5
