### ISSUE TITLE
установить imfit и другие пакеты для декомпозиции

### ISSUE THREAD

**Issue by Amarchuk** [alekskryzh/X-galaxies#2]
Поставить все, что описано в [этом](https://docs.google.com/document/d/1rzZuFAaTtuvw4VRX0n9HlhoocXs3LsdpFLinLHAt79g/edit) документе.

**Comment by alekskryzh** [comment]
Добрый день, всё поставил. А нужно регистрироваться на сервере и оптправлять файл с ключом на savchenko.s.s@gmail.com?

**Comment by Amarchuk** [comment]
Нет, не нужно.
